import fs from "node:fs/promises";
const BINANCE_CMS = "https://www.binance.com/bapi/apex/v1/public/apex/cms/article/list/query";
const BINANCE_BASE = "https://www.binance.com";
const CATALOG_ID = 93;
const LOOKBACK_MS = 14 * 24 * 3600e3;
function clean(s) { return (s || "").replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/&lt;/gi,"<").replace(/&gt;/gi,">").replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/\s+/g," ").trim(); }
async function getJson(url) { const res=await fetch(url,{headers:{"User-Agent":"SquareRadar/1.0","Accept-Language":"en","lang":"en","Referer":"https://www.binance.com/en/messages/v2/group/announcement"}}); if(!res.ok) throw new Error("Binance CreatorPad discovery HTTP "+res.status); return res.json(); }
function parseDateRange(text) { const m=text.match(/Activity\s+Period\s*:\s*([\s\S]{0,240}?)(?:Token\s+(?:Voucher\s+)?Rewards|How\s+to\s+Participate)/i); if(!m) return null; const dates=[...m[1].matchAll(/(\d{4}-\d{2}-\d{2}[ T]\d{2}:\d{2}(?::\d{2})?\s*\(UTC\)|\d{2}\.\d{2}\.\d{4}\s+\d{2}:\d{2}\s*\(UTC\))/gi)].map(x=>x[1]); if(dates.length<2) return null; const norm=d=>d.includes(".")?d.replace(/(\d{2})\.(\d{2})\.(\d{4})\s+(.*)/,"$3-$2-$1T$4"):d.replace(/\s*\(UTC\)/i,"").replace(" ","T"); const start=new Date(norm(dates[0])).getTime(), end=new Date(norm(dates[1])).getTime(); return Number.isFinite(start)&&Number.isFinite(end)?{start,end}:null; }
function reqs(text,title) { const h=(text.match(/hashtag\s+#([A-Za-z0-9_-]+)/i)||[])[1]||(text.match(/#([A-Za-z][A-Za-z0-9_-]{1,30})/)||[])[1]||""; const t=(text.match(/\$([A-Z][A-Z0-9]{1,14})\b/)||[])[1]||""; const a=(text.match(/(?:mention|account)[^@]{0,100}(@[A-Za-z0-9_.-]+)/i)||[])[1]||(text.match(/(@[A-Za-z0-9_.-]{2,40})/)||[])[1]||""; const min=Number((text.match(/minimum\s+(?:of\s+)?(\d+)\s+characters/i)||[])[1]||100); const max=Number((text.match(/(?:no more than|maximum(?: of)?)\s+(\d+)\s+characters/i)||[])[1]||0); const trade=(text.match(/(?:trade|trading)[^$\d]{0,40}\$?([\d,]+(?:\.\d+)?)\s+equivalent/i)||[])[1]||""; return {hashtag:h?"#"+h.replace(/^#/,""):"",token:t?"$"+t:"",mention:a,minChars:min,maxChars:max,trade,title}; }
function facts(text) { return text.split(/(?<=[.!?])\s+/).filter(x=>x.length>=45&&!/activity period|token voucher rewards|join now|how to participate|disclaimer|binance reserves|trade a minimum|follow.*account/i.test(x)).slice(0,4); }
function buildPost(c,f) { const tags=[c.hashtag,c.token,c.mention].filter(Boolean).join(" "); const base="A detail from the latest "+c.project+" update caught my attention:\n\n"+f.slice(0,3).join(" ")+"\n\nThe useful part is understanding what this changes for the project rather than simply repeating the reward headline.\n\n"+tags; const min=c.minChars||100; const max=c.maxChars||0; if(base.length<min) return (base+"\nThis is worth following for concrete product, ecosystem and user developments.").slice(0,max||undefined); return max&&base.length>max?base.slice(0,max-tags.length-2).trim()+"\n\n"+tags:base; }
export async function discoverCreatorPadCampaign() { const u=new URL(BINANCE_CMS); u.searchParams.set("type","1");u.searchParams.set("pageNo","1");u.searchParams.set("pageSize","30");u.searchParams.set("catalogId",String(CATALOG_ID)); const data=await getJson(u.href); const articles=(data?.data?.catalogs||[]).flatMap(c=>c.articles||[]); const now=Date.now(); for(const a of articles.filter(x=>/creatorpad/i.test(x.title)&&now-Number(x.releaseDate||0)<LOOKBACK_MS)){ const link=BINANCE_BASE+"/en/support/announcement/"+a.code; try { const r=await fetch(link,{headers:{"User-Agent":"SquareRadar/1.0","Accept-Language":"en"}}); if(!r.ok) continue; const body=clean(await r.text()); const range=parseDateRange(body); if(!range||now<range.start||now>range.end) continue; const q=reqs(body,a.title); if(!q.token||!q.hashtag) continue; const project=((a.title.match(/(?:for|of|share of)\s+(?:[\d,]+\s+)?([A-Za-z0-9 ._-]+?)(?:\s+Rewards|\s+Token|\s+on CreatorPad|\s*$)/i)||[])[1]||a.title).trim(); const fs=facts(body); if(!fs.length) continue; return {id:a.code,title:a.title,link,project,start:range.start,end:range.end,...q,facts:fs,post:buildPost({project,...q},fs)}; } catch {} } return null; }
export function campaignOutput(c,date) { if(!c) return "🟣 SQUARERADAR • "+date+"\n\n💰 CREATORPAD\nNo active public CreatorPad campaign was discovered from Binance latest activities.\n"; return ["🟣 SQUARERADAR • "+date,"\n💰 CREATORPAD OPPORTUNITY",c.title,"\n🏷️ "+[c.hashtag,c.token,c.mention].filter(Boolean).join(" "), "\n⏳ Ends: "+new Date(c.end).toISOString(), c.trade?"💱 Trade requirement: $"+c.trade+" equivalent":"💱 Trade requirement: not parsed","\n✍️ AUTO-PUBLISHED COPY",c.post,"\n🔗 Binance announcement\n"+c.link].join("\n"); }
export async function loadCampaignHistory(file) { try { const x=JSON.parse(await fs.readFile(file,"utf8")); return Array.isArray(x)?x:[]; } catch { return []; } }
export async function saveCampaignHistory(file,h) { await fs.writeFile(file,JSON.stringify(h.slice(-40),null,2)+"\n","utf8"); }